### PR TITLE
Support Linux on Apple

### PR DESCRIPTION
**Pull request by asdfugil**
[Linux on Apple](https://github.com/konradybcio/linux-apple) supports booting Linux on more checkm8 devices.

### CODE REVIEW

**Comment by raspberryenvoie** [comment]
Looks great! Have you tried to build the image and to use Linux on Apple? If everything's fine, it can be merged.

**Comment by asdfugil** [comment]
works on my iPhone X (Global)

**Comment by raspberryenvoie** [comment]
Thank you for your PR

**Comment by raspberryenvoie** [comment]
v2.15 ships with your changes!

**Pull request merged**
