### PR TITLE
linux-apple fixes

### PR DESCRIPTION
**Pull request by asdfugil**
Fix tunables on A9(X) (fix booting issues)
Fix iPad Pro (10.5-inch) and iPhone 8 Plus framebuffer

- A9 still broken due to another issue

### CODE REVIEW

**Comment by asdfugil** [comment]
converted to draft because on A9 there are issues with the initial ramdisk supposedly corrupting. (Works fine on A9X)

**Comment by raspberryenvoie** [comment]
Thanks! Once this is fixed, it will be ready for merging.

**Comment by raspberryenvoie** [comment]
How about adding to the odysseyn1x install scripts commands to build linux-apple? This would save from manually rebuilding linux-apple every time it gets updated.

**Comment by asdfugil** [comment]
> How about adding to the odysseyn1x install scripts commands to build linux-apple? This would save from manually rebuilding linux-apple every time it gets updated.

Well, if that is done then the linux-apple kernel will be built every time odysseyn1x is built, which is rather time consuming.

**Comment by raspberryenvoie** [comment]
How long is it to build linux-apple?

**Comment by asdfugil** [comment]
it varies wildly between build machines but it takes > 40 minutes to build the kernels on GitHub action runners.

**Comment by raspberryenvoie** [comment]
Yeah, I see

**Comment by asdfugil** [comment]
Let's not let A9 drag the other devices :)

**Comment by asdfugil** [comment]
@raspberryenvoie all fixed!

**Comment by asdfugil** [comment]
based on https://github.com/konradybcio/linux-apple/commit/753a54e5bf216d45b5c008cd7037020b5fea9f87

**Comment by asdfugil** [comment]
by the way i probably will have another PR incoming soon, for working around A8X/A9X `Found corrupted kerninfo!`

**Comment by raspberryenvoie** [comment]
Okay thank you!

**Pull request merged**
